### PR TITLE
add copy Button functionality

### PR DESCRIPTION
**Pull request by FirstZero**

### CODE REVIEW

**Comment by Epictek** [comment]
What browsers does this work in?

**Comment by FirstZero** [comment]
@Epictek works fine with chrome and firefox
Cant test IE, I am on linux..

**Comment by xiprox** [comment]
Will test with Safari :^)

**Comment by Epictek** [comment]
What about mobile support?

**Comment by Epictek** [comment]
[LGTM](http://lgtm.in/i/gmbLdUk6q)

[:+1:](http://lgtm.in/u/gmbLdUk6q) [:-1:](http://lgtm.in/r/gmbLdUk6q)

**Pull request merged**
